---
title: "Random Forest, Individual ARGs"
author: "Alessandro Zulli"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: united
  pdf_document:
    toc: yes
---

# Libraries

```{r, warning=FALSE, echo=FALSE}
# Load the package
library(readxl)
library(dplyr)
library(lubridate)
library(stringr)
library(googlesheets4)
library(writexl)
library(tidyr)
library("FactoMineR") #for multivariate exploratory data analysis
library(ggplot2) #for plotting
library("factoextra") #for visualizing outputs of PCA
library(plotly) #for interactive plotting
library(caret)
library(tigris)
library(tidygeocoder)
library(maps)
library(sf)
library(tidycensus)
library(ggplot2)
library(viridis)
library(doParallel)
library("svglite")



#get wastewaterSCAN data
SCAN_data <-read.csv("https://storage.googleapis.com/wastewater-dev-data/scan.csv") 
#get SCAN metadata
SCAN_metadata <- SCAN_data%>%dplyr::select(Sample_ID, Collection_Date, Population_Served,Plant, Site_Name, Zipcode, County_FIPS, PMMoV_gc_g_dry_weight)%>%distinct() 
names(SCAN_metadata)
#get counties
SCAN_counties <- SCAN_metadata%>%dplyr::select(Plant, County_FIPS)%>%distinct() %>% rename(plant=Plant)
#get AMR burden data
burden_data <- read.csv('/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/data_all.csv')%>% filter(city!="Modesto")%>%select(-fips)%>%rename(pop_km2=pop_km2_county)#%>%rename(All_cattle="CATTLE..INCL.CALVES...INVENTORY", All_chickens ="CHICKEN..TOTAL" , Hogs="HOGS...INVENTORY")
#merge with counties
burden_data <- burden_data %>%merge(SCAN_counties)
burden_data$County_FIPS <- sub(",.*", "", burden_data$County_FIPS)

counties <- counties(cb = TRUE, resolution = "20m") %>%
  sf::st_as_sf() %>% mutate(County_FIPS = paste0(STATEFP, COUNTYFP)) %>% dplyr::select(County_FIPS, geometry) 


nationwide_data <- read.csv('/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/USCounties_secondary_data_arg_2_23_25.csv')%>%dplyr::select(-Broilers, -Layers, -Pullets, -Roosters)%>%
  dplyr::select(-contains("count", ignore.case = TRUE))%>%
  dplyr::select(-contains("RPL", ignore.case = TRUE))%>%
  dplyr::select(-contains("E_", ignore.case = TRUE))%>%mutate(GEOID = str_pad(GEOID, width = 5, side = "left", pad = "0"))%>%rename(County_FIPS=GEOID)%>%na.omit()


# Set up parallel processing
cores <- detectCores() - 2  # Use all cores except 2
cl <- makeCluster(cores)
registerDoParallel(cl)

unique_locations <- burden_data %>%distinct(site, state, plant)

```

# Functions to make models and print the map from now on
## Currently on norm_S, removing -PROP_AIAN, -PROP_NHPI, -PROP_TWOMORE, -PROP_OTHERRACE, -PROP_MUNIT, -PROP_GROUPQ
```{r, warning=FALSE}


train_RF_model <- function(burden_data, target, numtrees=1000, tune_num=15, fold_validation=20) {
  # Filter data for specific target
  target_data <- burden_data %>% filter(target == !!target)
  
  # Get unique county FIPS
  unique_counties <- target_data %>% distinct(County_FIPS)
  
  # Prepare numerical data for modeling
  numerical_data <- target_data %>%
    mutate(original_order = row_number()) %>%
    group_by(County_FIPS) %>% dplyr::slice(1) %>%
    ungroup() %>%
    arrange(original_order) %>%
    select(-original_order) %>%
    dplyr::select(-city, -state, -site, -plant,
          -mean_ARG_P, -mean_ARG_B, -mean_ARG_S, -n, -mean_PMMoV, -mean_16S, -mean_rpoB, -mean_ARG_raw, -norm_ARG_B, -norm_ARG_P, -ratio_P, -ratio_S, -ratio_B,
         -nCT_svi, -nCT_eji, -RPL_EJI, -RPL_SER, -RPL_SVM, -RPL_EBM, -RPL_HVM, 
         -County,-County_FIPS, -Carbapenems_norm, -blactam_norm, -Tetracycline_norm, -Vancomycin_norm, -Colistin_norm, -TotalEncounters,-Region,-Division, -zipcode, -target, -zscore, -population, -PROP_AIAN, -PROP_NHPI, -PROP_TWOMORE, -PROP_OTHERRACE, -PROP_MUNIT, -PROP_GROUPQ, -PROP_MINRTY
    ) %>% mutate(total_airports = percent_rank(total_airports)*100, total_nursing =percent_rank(total_nursing)*100 ,total_hospitals =percent_rank(total_hospitals)*100)  %>%
    select(-contains("count_", ignore.case = TRUE)) %>%
    select(-contains("RPL", ignore.case = TRUE)) %>%
    select(-contains("E_", ignore.case = TRUE)) %>%
    mutate(across(everything(), ~replace_na(., 0)))
  
  # Set up cross-validation control
  ctrl <- trainControl(method = "cv", number = fold_validation, allowParallel = TRUE)
  
  # Train random forest model
  model_RF <- train(
    norm_ARG_S ~ .,
    data = numerical_data,
    method = "rf",
    trControl = ctrl,
    tuneLength = tune_num,
    ntree = numtrees
  )
  
  return(model_RF)
}

create_prediction_map <- function(model_RF, target_data, nationwide_data, counties, target_name) {
  
    # Filter data for specific target
  target_data <- burden_data %>% filter(target == !!target_name)
  
  # Get unique county FIPS
  unique_counties <- target_data %>% distinct(County_FIPS)
  
  # Prepare numerical data for modeling
  numerical_data <- target_data %>%
    mutate(original_order = row_number()) %>%
    group_by(County_FIPS) %>% 
    dplyr::slice(1) %>%
    ungroup() %>%
    arrange(original_order) %>%
    select(-original_order) %>%
    dplyr::select(-city, -state, -site, -plant,
         -mean_ARG_raw, -mean_ARG_P, -mean_ARG_B, -mean_ARG_S, -n, -mean_PMMoV, -mean_16S, -mean_rpoB, -norm_ARG_P, -norm_ARG_B, -ratio_P, -ratio_S, -ratio_B,
         -nCT_svi, -nCT_eji, -RPL_EJI, -RPL_SER, -RPL_SVM, -RPL_EBM, -RPL_HVM, 
         -County,-County_FIPS, -Carbapenems_norm, -blactam_norm, -Tetracycline_norm, -Vancomycin_norm, -Colistin_norm, -TotalEncounters,-Region,-Division, -zipcode, -target, -zscore, -population
    ) %>%
    select(-contains("count_", ignore.case = TRUE)) %>%
    select(-contains("RPL", ignore.case = TRUE)) %>%
    select(-contains("E_", ignore.case = TRUE)) %>%
    mutate(across(everything(), ~replace_na(., 0)))
  
  # Prepare data for predictions
  get_order <- numerical_data %>% select(-norm_ARG_S)
  
  # Get data for generating predictions
  data_for_predictions <- nationwide_data %>% 
    select(all_of(colnames(get_order)))
  
  # Generate predictions and prepare for mapping
  predictions_nationwide <- as.data.frame(predict(model_RF, newdata = data_for_predictions)) %>% 
    mutate(County_FIPS = nationwide_data$County_FIPS) %>%
    full_join(counties) %>%
    rename(Predicted = "predict(model_RF, newdata = data_for_predictions)") %>%
    mutate(quintile = ntile(Predicted, 5) * 20)
    # Get census regions - this requires the tigris package
  census_regions <- regions(resolution = "500k", year = 2020)
  
  # You can also use divisions for more detailed boundaries
  census_divisions <- divisions(resolution = "500k", year = 2020)
    
  # Create the map
  map_plot <- ggplot(data = predictions_nationwide) +
    geom_sf(aes(geometry = geometry, fill = factor(quintile)), 
            color = "white", 
            size = 0.1) +
  # Second layer: Census region boundaries with thick black outline
  geom_sf(data = census_regions,
          fill = NA,
          color = "black",
          linewidth = 0.5) +
  scale_fill_brewer(palette = "Reds",
                   name = "Percentile",
                   labels = c("0-20", "21-40", "41-60", "61-80", "81-100"))+
    theme_minimal() +
    theme(
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      panel.grid = element_blank(),
      plot.title = element_text(hjust = 0.5)
    ) +
    labs(
      title = paste(target_name, "concentrations predicted by RF model")
    ) +
    coord_sf(xlim = c(-125, -65), ylim = c(25, 50))
    
  
  return(map_plot)
}

```

# CMY model
```{r}
#model_CMY <- train_RF_model(burden_data, "CMY")
print(model_CMY)
map <- create_prediction_map(
  model_RF = model_CMY,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "CMY"
)
print(map)

ggsave( "CMY.svg",map, width=10, height=7, dpi=600)

# Get variable importance
importance <- varImp(model_CMY)
# Plot importance
plot(importance, main="CMY Variable Importance")



svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/CMY_importance.svg")
plot(importance, main="CMY Variable Importance")
dev.off()



```

# CTX-M model 
```{r}
#model_CTXM <- train_RF_model(burden_data, "CTX-M")
print(model_CTXM)
map <- create_prediction_map(
  model_RF = model_CTXM,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "CTX-M"
)
print(map)

# Get variable importance
importance <- varImp(model_CTXM)
# Plot importance
plot(importance, main="CTXM Variable Importance")
ggsave( "CTXM.svg",map, width=10, height=7, dpi=600)


svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/CTXM_importance.svg")
plot(importance, main="CTXM Variable Importance")
dev.off()

```

# KPC model 
```{r}
#model_KPC <- train_RF_model(burden_data, "KPC")
print(model_KPC)
map <- create_prediction_map(
  model_RF = model_KPC,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "KPC"
)
print(map)

# Get variable importance
importance <- varImp(model_KPC)
# Plot importance
plot(importance, main="KPC Variable Importance")
ggsave( "KPC.svg",map, width=10, height=7, dpi=600)


svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/KPC_importance.svg")
plot(importance, main="KPC Variable Importance")
dev.off()
```

# MCR-1 model 
```{r}
#model_MCR1 <- train_RF_model(burden_data, "MCR-1")
print(model_MCR1)
map <- create_prediction_map(
  model_RF = model_MCR1,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "MCR-1"
)
print(map)
getwd()
ggsave( "MCR1.svg",map, width=10, height=7, dpi=600)
# Get variable importance
importance <- varImp(model_MCR1)

#view((importance))
# Plot importance
plot(importance, main="MCR-1 Variable Importance")

svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/MCR_1_importance.svg")
plot(importance, main="MCR-1 Variable Importance")
dev.off()

```

# MecA model 
```{r}
#model_MecA <- train_RF_model(burden_data, "MecA")
print(model_MecA)
map <- create_prediction_map(
  model_RF = model_MecA,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "MecA"
)
print(map)

# Get variable importance
importance <- varImp(model_MecA)
# Plot importance
plot(importance, main="MecA Variable Importance")
ggsave( "MecA.svg",map, width=10, height=7, dpi=600)

svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/MecA_importance.svg")
plot(importance, main="MecA Variable Importance")
dev.off()

```

# NDM model 
```{r}
#model_NDM <- train_RF_model(burden_data, "NDM")
print(model_NDM)
map <- create_prediction_map(
  model_RF = model_NDM,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "NDM"
)
print(map)

# Get variable importance
importance <- varImp(model_NDM)
# Plot importance
plot(importance, main="NDM Variable Importance")
ggsave( "NDM.svg",map, width=10, height=7, dpi=600)

svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/NDM_importance.svg")
plot(importance, main="NDM Variable Importance")
dev.off()

```

# OXA48 model 
```{r}
#model_OXA48 <- train_RF_model(burden_data, "OXA-48", fold_validation = 20)
print(model_OXA48)
map <- create_prediction_map(
  model_RF = model_OXA48,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "OXA-48"
)
print(map)

# Get variable importance
importance <- varImp(model_OXA48)
# Plot importance
plot(importance, main="OXA48 Variable Importance")

ggsave( "oxa48.svg",map, width=10, height=7, dpi=600)


svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/oxa48_importance.svg")
plot(importance, main="oxa48 Variable Importance")
dev.off()
```

# TEM model 
```{r}
#model_TEM <- train_RF_model(burden_data, "TEM")
print(model_TEM)
map <- create_prediction_map(
  model_RF = model_TEM,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "TEM"
)
print(map)

# Get variable importance
importance <- varImp(model_TEM)
# Plot importance
plot(importance, main="TEM Variable Importance")
ggsave( "TEM.svg",map, width=10, height=7, dpi=600)

svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/TEM_importance.svg")
plot(importance, main="TEM Variable Importance")
dev.off()

```

# Tetw model 
```{r}
#model_TetW <- train_RF_model(burden_data, "TetW")
print(model_TetW)
map <- create_prediction_map(
  model_RF = model_TetW,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "TetW"
)
print(map)

# Get variable importance
importance <- varImp(model_TetW)
# Plot importance
plot(importance, main="TetW Variable Importance")

ggsave( "tetw.svg",map, width=10, height=7, dpi=600)

svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/tetw_importance.svg")
plot(importance, main="tetw Variable Importance")
dev.off()

```


# VIM model
```{r}
#model_VIM <- train_RF_model(burden_data, "VIM")
print(model_VIM)
map <- create_prediction_map(
  model_RF = model_VIM,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "VIM"
)
print(map)

# Get variable importance
importance <- varImp(model_VIM)
# Plot importance
plot(importance, main="VIM Variable Importance")

ggsave( "VIM.svg",map, width=10, height=7, dpi=600)


svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/VIM_importance.svg")
plot(importance, main="VIM Variable Importance")
dev.off()
```

# VanA model 
```{r}

#model_VanA <- train_RF_model(burden_data, "VanA")
print(model_VanA)
map <- create_prediction_map(
  model_RF = model_VanA,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "VanA"
)
print(map)

# Get variable importance
importance <- varImp(model_VanA)
# Plot importance
plot(importance, main="VanA Variable Importance")
ggsave( "vanA.svg",map, width=10, height=7, dpi=600)


svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/vanA_importance.svg")
plot(importance, main="vanA Variable Importance")
dev.off()
```

# VanB model 
```{r}
#model_VanB <- train_RF_model(burden_data, "VanB")
print(model_VanB)
map <- create_prediction_map(
  model_RF = model_VanB,
  target_data = burden_data,
  nationwide_data = nationwide_data,
  counties = counties,
  target_name = "VanB"
)
print(map)

# Get variable importance
importance <- varImp(model_VanB)
# Plot importance
plot(importance, main="VanB Variable Importance")
ggsave( "vanB.svg",map, width=10, height=7, dpi=600)

svg(filename="/Users/zulli/Library/CloudStorage/GoogleDrive-azulli@stanford.edu/My Drive/Boehm Drive/Antibiotic Resistance Project/Importance/vanB_importance.svg")
plot(importance, main="vanB Variable Importance")
dev.off()

```

```{r}
  numerical_data <- burden_data %>%
    mutate(original_order = row_number()) %>%
    group_by(County_FIPS) %>% 
    dplyr::slice(1) %>%
    ungroup() %>%
    arrange(original_order) %>%
    select(-original_order) %>%
    dplyr::select(-city, -state, -site, -plant, -norm_ARG_S,
          -mean_ARG_P, -mean_ARG_B, -mean_ARG_S, -n, -mean_PMMoV, -mean_16S, -mean_rpoB, -mean_ARG_raw, -norm_ARG_B, -norm_ARG_P, -ratio_P, -ratio_S, -ratio_B,
         -nCT_svi, -nCT_eji, -RPL_EJI, -RPL_SER, -RPL_SVM, -RPL_EBM, -RPL_HVM, 
         -County,-County_FIPS, -Carbapenems_norm, -blactam_norm, -Tetracycline_norm, -Vancomycin_norm, -Colistin_norm, -TotalEncounters,-Region,-Division, -zipcode, -target, -zscore, -population
    ) %>% mutate(total_airports = round(percent_rank(total_airports)*100/25,0), total_nursing = round(percent_rank(total_nursing)*100/25,0),total_hospitals = round(percent_rank(total_hospitals)*100/25,0)) %>%
    select(-contains("count_", ignore.case = TRUE)) %>%
    select(-contains("RPL", ignore.case = TRUE)) %>%
    select(-contains("E_", ignore.case = TRUE)) %>%
    mutate(across(everything(), ~replace_na(., 0)))

# Calculate correlation matrix
cor_matrix <- cor(numerical_data, use="pairwise.complete.obs")

# Visualize correlation matrix
library(corrplot)
corrplot(cor_matrix, method="circle", type="upper", 
         tl.col="black", tl.cex=0.7)

```

